"""
concorrencia_config.py
Configuração por marca do pipeline de inteligência competitiva (scripts 11-15).

Para adicionar uma marca: criar a entrada em MARCAS (concorrentes do Censo,
praças, cores, municípios de benchmark) e rodar 11 -> 12 -> 14 -> 15 -> 13
passando o nome da marca como argumento.

Unidades infantis das redes (ex.: Planeta Mágico do Alfa CEM, Pensi Casulo)
ficam de fora - não têm 3º ano.
"""

MARCAS: dict[str, dict] = {
    # ──────────────────────────────────────────────────────────────────────
    "Matriz Educação": {
        "slug": "matriz",
        "curto": "Matriz",
        "cor": "#15803d",
        "tile": "#0a4d2b",
        "logo": "Matriz_Educação.imgtag",
        "html_out": "Concorrencia_Matriz.html",
        "deploy_file": "matriz.html",
        "hero_sub": "Comparação unidade a unidade com Elite, Santa Mônica e ZeroHum · Microdados INEP · Uso interno",
        "municipios_bench": {3304557: "Rio de Janeiro", 3301702: "Duque de Caxias",
                             3303500: "Nova Iguaçu", 3305109: "São João de Meriti"},
        "confronto_default": [33183368, 33520321],
        "cores_redes": {"Elite": "#1d4ed8", "Santa Mônica": "#be123c", "ZeroHum": "#b45309"},
        "concorrentes": {
            "Elite": {
                33520321: {"label": "Campo Grande I",      "municipio": "Rio de Janeiro",     "bairro": "CAMPO GRANDE"},
                33520330: {"label": "Campo Grande II",     "municipio": "Rio de Janeiro",     "bairro": "SENADOR VASCONCELOS"},
                33169713: {"label": "Taquara",             "municipio": "Rio de Janeiro",     "bairro": "TAQUARA"},
                33159130: {"label": "Bangu",               "municipio": "Rio de Janeiro",     "bairro": "BANGU"},
                33122245: {"label": "Realengo",            "municipio": "Rio de Janeiro",     "bairro": "REALENGO"},
                33140626: {"label": "Madureira 1",         "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33149780: {"label": "Madureira 2",         "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33531218: {"label": "Madureira 3",         "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33162999: {"label": "Norte Shopping",      "municipio": "Rio de Janeiro",     "bairro": "CACHAMBI"},
                33152276: {"label": "Tijuca",              "municipio": "Rio de Janeiro",     "bairro": "TIJUCA"},
                33193649: {"label": "Irajá",               "municipio": "Rio de Janeiro",     "bairro": "IRAJA"},
                33193720: {"label": "Guadalupe",           "municipio": "Rio de Janeiro",     "bairro": "GUADALUPE"},
                33195757: {"label": "Bonsucesso",          "municipio": "Rio de Janeiro",     "bairro": "BONSUCESSO"},
                33172331: {"label": "Ilha do Governador",  "municipio": "Rio de Janeiro",     "bairro": "JARDIM GUANABARA"},
                33125228: {"label": "Santa Cruz",          "municipio": "Rio de Janeiro",     "bairro": "SANTA CRUZ"},
                33526249: {"label": "Vila Valqueire",      "municipio": "Rio de Janeiro",     "bairro": "VILA VALQUEIRE"},
                33173850: {"label": "Duque de Caxias",     "municipio": "Duque de Caxias",    "bairro": "CENTRO"},
                33060355: {"label": "Iguaçuano",           "municipio": "Nova Iguaçu",        "bairro": "CENTRO"},
                33526214: {"label": "Nova Iguaçu (Luz)",   "municipio": "Nova Iguaçu",        "bairro": "DA LUZ"},
                33176752: {"label": "São João de Meriti",  "municipio": "São João de Meriti", "bairro": "CENTRO"},
                33182884: {"label": "Nilópolis",           "municipio": "Nilópolis",          "bairro": "NILOPOLIS"},
                33195978: {"label": "Itaguaí",             "municipio": "Itaguaí",            "bairro": "PROGRESSO"},
                33139032: {"label": "São Gonçalo",         "municipio": "São Gonçalo",        "bairro": "CENTRO"},
                33184844: {"label": "Três Rios",           "municipio": "Três Rios",          "bairro": "CENTRO"},
            },
            "Santa Mônica": {
                33113114: {"label": "Campo Grande",        "municipio": "Rio de Janeiro",     "bairro": "CAMPO GRANDE"},
                33111642: {"label": "Taquara (Colégio)",   "municipio": "Rio de Janeiro",     "bairro": "TAQUARA"},
                33173907: {"label": "Taquara (Rede)",      "municipio": "Rio de Janeiro",     "bairro": "TAQUARA"},
                33094861: {"label": "Madureira",           "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33071926: {"label": "Cachambi",            "municipio": "Rio de Janeiro",     "bairro": "CACHAMBI"},
                33075581: {"label": "Cascadura",           "municipio": "Rio de Janeiro",     "bairro": "CASCADURA"},
                33075603: {"label": "Bento Ribeiro A",     "municipio": "Rio de Janeiro",     "bairro": "BENTO RIBEIRO"},
                33075620: {"label": "Bento Ribeiro B",     "municipio": "Rio de Janeiro",     "bairro": "BENTO RIBEIRO"},
                33088519: {"label": "Bonsucesso",          "municipio": "Rio de Janeiro",     "bairro": "BONSUCESSO"},
                33085609: {"label": "Ilha do Governador",  "municipio": "Rio de Janeiro",     "bairro": "JARDIM GUANABARA"},
                33084262: {"label": "Santa Cruz",          "municipio": "Rio de Janeiro",     "bairro": "SANTA CRUZ"},
                33148937: {"label": "Freguesia",           "municipio": "Rio de Janeiro",     "bairro": "FREGUESIA"},
                33160031: {"label": "Recreio",             "municipio": "Rio de Janeiro",     "bairro": "RECREIO"},
                33100985: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro",     "bairro": "BARRA DA TIJUCA"},
                33139458: {"label": "Duque de Caxias",     "municipio": "Duque de Caxias",    "bairro": "JARDIM ANHANGA"},
                33185000: {"label": "Liceu (N. Iguaçu)",   "municipio": "Nova Iguaçu",        "bairro": "KENNEDY"},
                33197946: {"label": "Nilópolis",           "municipio": "Nilópolis",          "bairro": "CENTRO"},
                33115478: {"label": "Maricá",              "municipio": "Maricá",             "bairro": "CENTRO"},
                33089825: {"label": "São Gonçalo",         "municipio": "São Gonçalo",        "bairro": "MUTUA"},
                33112657: {"label": "Seropédica",          "municipio": "Seropédica",         "bairro": "PIRANEMA"},
            },
            "ZeroHum": {
                33185476: {"label": "Centro",              "municipio": "Rio de Janeiro",     "bairro": "CENTRO"},
                33193495: {"label": "Maracanã",            "municipio": "Rio de Janeiro",     "bairro": "MARACANA"},
                33067821: {"label": "Vila Isabel",         "municipio": "Rio de Janeiro",     "bairro": "VILA ISABEL"},
                33105138: {"label": "Méier",               "municipio": "Rio de Janeiro",     "bairro": "MEIER"},
                33197350: {"label": "Madureira",           "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33394202: {"label": "Olaria",              "municipio": "Rio de Janeiro",     "bairro": "OLARIA"},
                33183155: {"label": "Galeão",              "municipio": "Rio de Janeiro",     "bairro": "GALEAO"},
                33202850: {"label": "Ilha do Governador",  "municipio": "Rio de Janeiro",     "bairro": "GALEAO"},
                33187681: {"label": "Nova Iguaçu",         "municipio": "Nova Iguaçu",        "bairro": "CENTRO"},
                33198926: {"label": "Da Prata",            "municipio": "Nova Iguaçu",        "bairro": "VILA CATIA"},
                33200572: {"label": "S. J. de Meriti",     "municipio": "São João de Meriti", "bairro": "JARDIM JOSE BONIFACIO"},
                33185700: {"label": "Jardim Metrópole",    "municipio": "São João de Meriti", "bairro": "JARDIM METROPOLE"},
                33193444: {"label": "Nilópolis",           "municipio": "Nilópolis",          "bairro": "CENTRO"},
                33199949: {"label": "Belford Roxo",        "municipio": "Belford Roxo",       "bairro": "CENTRO"},
                33176787: {"label": "Niterói Centro",      "municipio": "Niterói",            "bairro": "CENTRO"},
                33055416: {"label": "Icaraí",              "municipio": "Niterói",            "bairro": "ICARAI"},
                33193991: {"label": "Itaipu",              "municipio": "Niterói",            "bairro": "ITAIPU"},
                33179301: {"label": "São Gonçalo",         "municipio": "São Gonçalo",        "bairro": "PARAISO"},
                33180660: {"label": "Alcântara",           "municipio": "São Gonçalo",        "bairro": "ALCANTARA"},
                33186928: {"label": "Maricá Centro",       "municipio": "Maricá",             "bairro": "CENTRO"},
                33203130: {"label": "Maricá Barroco",      "municipio": "Maricá",             "bairro": "BARROCO"},
                33166951: {"label": "Araruama",            "municipio": "Araruama",           "bairro": "CENTRO"},
                33184666: {"label": "Cabo Frio",           "municipio": "Cabo Frio",          "bairro": "PARQUE RIVIERA"},
                33196826: {"label": "Itaboraí",            "municipio": "Itaboraí",           "bairro": "CENTRO"},
                33021678: {"label": "Nova Friburgo",       "municipio": "Nova Friburgo",      "bairro": "CORDOEIRA"},
                33200068: {"label": "Volta Redonda",       "municipio": "Volta Redonda",      "bairro": "VILA SANTA CECILIA"},
            },
        },
        "pracas": [
            {"titulo": "Campo Grande", "municipio": "Rio de Janeiro", "nossa": 33183368,
             "diretos": [33520321, 33113114], "adjacentes": [],
             "nota": "Elite Campo Grande II (Senador Vasconcelos) sem dados no ENEM 2024 e 2025."},
            {"titulo": "Taquara", "municipio": "Rio de Janeiro", "nossa": 33187770,
             "diretos": [33169713, 33111642, 33173907], "adjacentes": [], "nota": ""},
            {"titulo": "Bangu", "municipio": "Rio de Janeiro", "nossa": 33187789,
             "diretos": [33159130], "adjacentes": [33122245],
             "nota": "Elite Realengo exibido como praça adjacente."},
            {"titulo": "Madureira", "municipio": "Rio de Janeiro", "nossa": 33197466,
             "diretos": [33140626, 33149780, 33094861, 33197350], "adjacentes": [],
             "nota": "Elite Madureira 3 sem dados no ENEM 2024 e 2025."},
            {"titulo": "Rocha Miranda", "municipio": "Rio de Janeiro", "nossa": 33192685,
             "diretos": [], "adjacentes": [33193649, 33193720],
             "nota": "Sem concorrente mapeado no bairro - exibidos os mais próximos (Irajá e Guadalupe)."},
            {"titulo": "Nova Iguaçu", "municipio": "Nova Iguaçu", "nossa": 33187762,
             "diretos": [33060355, 33185000, 33187681], "adjacentes": [33198926],
             "nota": "Elite Nova Iguaçu (bairro da Luz) sem dados no ENEM 2024 e 2025."},
            {"titulo": "Duque de Caxias", "municipio": "Duque de Caxias", "nossa": 33048185,
             "diretos": [], "adjacentes": [], "ref2024": [33173850],
             "nota": "O Elite de Caxias pontuou no ENEM 2024 (referência acima) e não registrou participantes em 2025. Santa Mônica de Caxias sem dados nos dois anos."},
            {"titulo": "São João de Meriti", "municipio": "São João de Meriti", "nossa": 33190674,
             "diretos": [33200572], "adjacentes": [], "ref2024": [33176752, 33185700],
             "nota": "Elite S. J. de Meriti e ZeroHum Jardim Metrópole pontuaram no ENEM 2024 (referências acima) e não registraram participantes em 2025."},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    "QI Bilíngue": {
        "slug": "qi",
        "curto": "QI",
        "cor": "#6d28d9",
        "tile": "#4c1d95",
        "logo": "QI_Bilíngue.imgtag",
        "html_out": "Concorrencia_QI.html",
        "deploy_file": "qi.html",
        "hero_sub": "Comparação unidade a unidade com Pensi, Alfa CEM, pH e AZ · Microdados INEP · Uso interno",
        "municipios_bench": {3304557: "Rio de Janeiro"},
        "confronto_default": [33135924, 33161011],
        "cores_redes": {"Pensi": "#1d4ed8", "Alfa CEM": "#0f766e", "pH": "#be123c", "AZ": "#b45309"},
        "concorrentes": {
            "Pensi": {
                33135827: {"label": "Maracanã",            "municipio": "Rio de Janeiro", "bairro": "MARACANA"},
                33166820: {"label": "Tijuca",              "municipio": "Rio de Janeiro", "bairro": "TIJUCA"},
                33067813: {"label": "Martins Vila Isabel", "municipio": "Rio de Janeiro", "bairro": "VILA ISABEL"},
                33071683: {"label": "Martins Méier",       "municipio": "Rio de Janeiro", "bairro": "MEIER"},
                33161011: {"label": "Freguesia",           "municipio": "Rio de Janeiro", "bairro": "FREGUESIA"},
                33138028: {"label": "Recreio 1",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33161402: {"label": "Recreio 2",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33193118: {"label": "Flamengo",            "municipio": "Rio de Janeiro", "bairro": "FLAMENGO"},
                33421226: {"label": "Copacabana",          "municipio": "Rio de Janeiro", "bairro": "COPACABANA"},
                33166935: {"label": "Jardim Carioca",      "municipio": "Rio de Janeiro", "bairro": "JARDIM CARIOCA"},
                33166943: {"label": "Madureira",           "municipio": "Rio de Janeiro", "bairro": "MADUREIRA"},
                33191824: {"label": "Vila da Penha",       "municipio": "Rio de Janeiro", "bairro": "VILA DA PENHA"},
                33057451: {"label": "Icaraí 1",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33150931: {"label": "Icaraí 2",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33165920: {"label": "Icaraí 3",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33161429: {"label": "Itaipu",              "municipio": "Niterói",        "bairro": "ITAIPU"},
                33027781: {"label": "Cabo Frio 1",         "municipio": "Cabo Frio",      "bairro": "CENTRO"},
                33178968: {"label": "Cabo Frio 2",         "municipio": "Cabo Frio",      "bairro": "CENTRO"},
                33178976: {"label": "Cabo Frio 3",         "municipio": "Cabo Frio",      "bairro": "CENTRO"},
                33120544: {"label": "Campos",              "municipio": "Campos dos Goytacazes", "bairro": "CENTRO"},
                33178909: {"label": "Petrópolis",          "municipio": "Petrópolis",     "bairro": "CENTRO"},
                33182094: {"label": "Teresópolis",         "municipio": "Teresópolis",    "bairro": "ALTO"},
            },
            "Alfa CEM": {
                33178879: {"label": "Anil",                "municipio": "Rio de Janeiro", "bairro": "ANIL"},
                33184720: {"label": "Barra Olímpica",      "municipio": "Rio de Janeiro", "bairro": "BARRA OLIMPICA"},
                33184739: {"label": "Barra da Tijuca 1",   "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33196273: {"label": "Barra da Tijuca 2",   "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33188092: {"label": "Recreio 1",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33193258: {"label": "Recreio 2",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33202532: {"label": "Recreio 3",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
            },
            "pH": {
                33105405: {"label": "Tijuca",              "municipio": "Rio de Janeiro", "bairro": "TIJUCA"},
                33110328: {"label": "Botafogo 1",          "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33158240: {"label": "Botafogo 2",          "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33249202: {"label": "Leblon",              "municipio": "Rio de Janeiro", "bairro": "LEBLON"},
                33155852: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33177627: {"label": "Recreio",             "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33180539: {"label": "Freguesia",           "municipio": "Rio de Janeiro", "bairro": "FREGUESIA"},
                33153450: {"label": "Icaraí 1",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33177619: {"label": "Icaraí 2",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33180385: {"label": "Icaraí 3",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33165998: {"label": "Piratininga",         "municipio": "Niterói",        "bairro": "PIRATININGA"},
                33204039: {"label": "São João da Barra",   "municipio": "São João da Barra", "bairro": ""},
            },
            "AZ": {
                33173990: {"label": "Tijuca",              "municipio": "Rio de Janeiro", "bairro": "TIJUCA"},
                33228604: {"label": "Botafogo",            "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33447225: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33203431: {"label": "Recreio",             "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33223203: {"label": "Méier",               "municipio": "Rio de Janeiro", "bairro": "MEIER"},
                33175195: {"label": "Ilha",                "municipio": "Rio de Janeiro", "bairro": "JARDIM GUANABARA"},
            },
        },
        "pracas": [
            {"titulo": "Freguesia", "municipio": "Rio de Janeiro", "nossa": 33135924,
             "diretos": [33161011, 33180539], "adjacentes": [], "nota": ""},
            {"titulo": "Méier (Metropolitano)", "municipio": "Rio de Janeiro", "nossa": 33071721,
             "diretos": [33071683, 33223203], "adjacentes": [33067813], "nota": ""},
            {"titulo": "Recreio", "municipio": "Rio de Janeiro", "nossa": 33156026,
             "diretos": [33138028, 33161402, 33177627, 33203431, 33188092, 33193258, 33202532],
             "adjacentes": [], "nota": ""},
            {"titulo": "Rio 2 (Barra Olímpica)", "municipio": "Rio de Janeiro", "nossa": 33199400,
             "diretos": [33184720], "adjacentes": [33155852, 33447225, 33184739, 33196273],
             "nota": "Unidades da Barra da Tijuca exibidas como praças adjacentes."},
            {"titulo": "Rio 2 Bilíngue", "municipio": "Rio de Janeiro", "nossa": 33187924,
             "diretos": [33184720], "adjacentes": [33155852, 33447225, 33184739, 33196273],
             "nota": "A unidade QI - Rio 2 (regular) não registrou participantes no ENEM 2025; a praça é representada pela unidade bilíngue."},
            {"titulo": "Tijuca (Maracanã)", "municipio": "Rio de Janeiro", "nossa": 33124418,
             "diretos": [33135827, 33166820, 33105405, 33173990], "adjacentes": [], "nota": ""},
            {"titulo": "Botafogo", "municipio": "Rio de Janeiro", "nossa": 33143331,
             "diretos": [33110328, 33158240, 33228604], "adjacentes": [33193118],
             "nota": "A unidade QI Bilíngue Botafogo foi encerrada para 2026; dados referem-se a 2025."},
        ],
    },
}


def get_marca(argv: list) -> tuple[str, dict]:
    nome = argv[1] if len(argv) > 1 else "Matriz Educação"
    if nome not in MARCAS:
        raise SystemExit(f"Marca desconhecida: {nome}. Opções: {list(MARCAS)}")
    return nome, MARCAS[nome]
