"""
concorrencia_config.py
Configuração por marca do pipeline de inteligência competitiva (scripts 11-15).

Para adicionar uma marca: criar a entrada em MARCAS (concorrentes do Censo,
praças, cores, municípios de benchmark) e rodar 11 -> 12 -> 14 -> 15 -> 13
passando o nome da marca como argumento.

Unidades infantis das redes (ex.: Planeta Mágico do Alfa CEM, Pensi Casulo)
ficam de fora - não têm 3º ano.
"""

MARCAS: dict[str, dict] = {
    # ──────────────────────────────────────────────────────────────────────
    "Matriz Educação": {
        "slug": "matriz",
        "curto": "Matriz",
        "cor": "#15803d",
        "tile": "#0a4d2b",
        "logo": "Matriz_Educação.imgtag",
        "html_out": "Concorrencia_Matriz.html",
        "deploy_file": "matriz.html",
        "hero_sub": "Comparação unidade a unidade com Elite, Santa Mônica e ZeroHum · Microdados INEP · Uso interno",
        "municipios_bench": {3304557: "Rio de Janeiro", 3301702: "Duque de Caxias",
                             3303500: "Nova Iguaçu", 3305109: "São João de Meriti"},
        "confronto_default": [33183368, 33520321],
        "cores_redes": {"Elite": "#1d4ed8", "Santa Mônica": "#be123c", "ZeroHum": "#b45309"},
        "concorrentes": {
            "Elite": {
                33520321: {"label": "Campo Grande I",      "municipio": "Rio de Janeiro",     "bairro": "CAMPO GRANDE"},
                33520330: {"label": "Campo Grande II",     "municipio": "Rio de Janeiro",     "bairro": "SENADOR VASCONCELOS"},
                33169713: {"label": "Taquara",             "municipio": "Rio de Janeiro",     "bairro": "TAQUARA"},
                33159130: {"label": "Bangu",               "municipio": "Rio de Janeiro",     "bairro": "BANGU"},
                33122245: {"label": "Realengo",            "municipio": "Rio de Janeiro",     "bairro": "REALENGO"},
                33140626: {"label": "Madureira 1",         "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33149780: {"label": "Madureira 2",         "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33531218: {"label": "Madureira 3",         "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33162999: {"label": "Norte Shopping",      "municipio": "Rio de Janeiro",     "bairro": "CACHAMBI"},
                33152276: {"label": "Tijuca",              "municipio": "Rio de Janeiro",     "bairro": "TIJUCA"},
                33193649: {"label": "Irajá",               "municipio": "Rio de Janeiro",     "bairro": "IRAJA"},
                33193720: {"label": "Guadalupe",           "municipio": "Rio de Janeiro",     "bairro": "GUADALUPE"},
                33195757: {"label": "Bonsucesso",          "municipio": "Rio de Janeiro",     "bairro": "BONSUCESSO"},
                33172331: {"label": "Ilha do Governador",  "municipio": "Rio de Janeiro",     "bairro": "JARDIM GUANABARA"},
                33125228: {"label": "Santa Cruz",          "municipio": "Rio de Janeiro",     "bairro": "SANTA CRUZ"},
                33526249: {"label": "Vila Valqueire",      "municipio": "Rio de Janeiro",     "bairro": "VILA VALQUEIRE"},
                33173850: {"label": "Duque de Caxias",     "municipio": "Duque de Caxias",    "bairro": "CENTRO"},
                33060355: {"label": "Iguaçuano",           "municipio": "Nova Iguaçu",        "bairro": "CENTRO"},
                33526214: {"label": "Nova Iguaçu (Luz)",   "municipio": "Nova Iguaçu",        "bairro": "DA LUZ"},
                33176752: {"label": "São João de Meriti",  "municipio": "São João de Meriti", "bairro": "CENTRO"},
                33182884: {"label": "Nilópolis",           "municipio": "Nilópolis",          "bairro": "NILOPOLIS"},
                33195978: {"label": "Itaguaí",             "municipio": "Itaguaí",            "bairro": "PROGRESSO"},
                33139032: {"label": "São Gonçalo",         "municipio": "São Gonçalo",        "bairro": "CENTRO"},
                33184844: {"label": "Três Rios",           "municipio": "Três Rios",          "bairro": "CENTRO"},
            },
            "Santa Mônica": {
                33113114: {"label": "Campo Grande",        "municipio": "Rio de Janeiro",     "bairro": "CAMPO GRANDE"},
                33111642: {"label": "Taquara (Colégio)",   "municipio": "Rio de Janeiro",     "bairro": "TAQUARA"},
                33173907: {"label": "Taquara (Rede)",      "municipio": "Rio de Janeiro",     "bairro": "TAQUARA"},
                33094861: {"label": "Madureira",           "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33071926: {"label": "Cachambi",            "municipio": "Rio de Janeiro",     "bairro": "CACHAMBI"},
                33075581: {"label": "Cascadura",           "municipio": "Rio de Janeiro",     "bairro": "CASCADURA"},
                33075603: {"label": "Bento Ribeiro A",     "municipio": "Rio de Janeiro",     "bairro": "BENTO RIBEIRO"},
                33075620: {"label": "Bento Ribeiro B",     "municipio": "Rio de Janeiro",     "bairro": "BENTO RIBEIRO"},
                33088519: {"label": "Bonsucesso",          "municipio": "Rio de Janeiro",     "bairro": "BONSUCESSO"},
                33085609: {"label": "Ilha do Governador",  "municipio": "Rio de Janeiro",     "bairro": "JARDIM GUANABARA"},
                33084262: {"label": "Santa Cruz",          "municipio": "Rio de Janeiro",     "bairro": "SANTA CRUZ"},
                33148937: {"label": "Freguesia",           "municipio": "Rio de Janeiro",     "bairro": "FREGUESIA"},
                33160031: {"label": "Recreio",             "municipio": "Rio de Janeiro",     "bairro": "RECREIO"},
                33100985: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro",     "bairro": "BARRA DA TIJUCA"},
                33139458: {"label": "Duque de Caxias",     "municipio": "Duque de Caxias",    "bairro": "JARDIM ANHANGA"},
                33185000: {"label": "Liceu (N. Iguaçu)",   "municipio": "Nova Iguaçu",        "bairro": "KENNEDY"},
                33197946: {"label": "Nilópolis",           "municipio": "Nilópolis",          "bairro": "CENTRO"},
                33115478: {"label": "Maricá",              "municipio": "Maricá",             "bairro": "CENTRO"},
                33089825: {"label": "São Gonçalo",         "municipio": "São Gonçalo",        "bairro": "MUTUA"},
                33112657: {"label": "Seropédica",          "municipio": "Seropédica",         "bairro": "PIRANEMA"},
            },
            "ZeroHum": {
                33185476: {"label": "Centro",              "municipio": "Rio de Janeiro",     "bairro": "CENTRO"},
                33193495: {"label": "Maracanã",            "municipio": "Rio de Janeiro",     "bairro": "MARACANA"},
                33067821: {"label": "Vila Isabel",         "municipio": "Rio de Janeiro",     "bairro": "VILA ISABEL"},
                33105138: {"label": "Méier",               "municipio": "Rio de Janeiro",     "bairro": "MEIER"},
                33197350: {"label": "Madureira",           "municipio": "Rio de Janeiro",     "bairro": "MADUREIRA"},
                33394202: {"label": "Olaria",              "municipio": "Rio de Janeiro",     "bairro": "OLARIA"},
                33183155: {"label": "Galeão",              "municipio": "Rio de Janeiro",     "bairro": "GALEAO"},
                33202850: {"label": "Ilha do Governador",  "municipio": "Rio de Janeiro",     "bairro": "GALEAO"},
                33187681: {"label": "Nova Iguaçu",         "municipio": "Nova Iguaçu",        "bairro": "CENTRO"},
                33198926: {"label": "Da Prata",            "municipio": "Nova Iguaçu",        "bairro": "VILA CATIA"},
                33200572: {"label": "S. J. de Meriti",     "municipio": "São João de Meriti", "bairro": "JARDIM JOSE BONIFACIO"},
                33185700: {"label": "Jardim Metrópole",    "municipio": "São João de Meriti", "bairro": "JARDIM METROPOLE"},
                33193444: {"label": "Nilópolis",           "municipio": "Nilópolis",          "bairro": "CENTRO"},
                33199949: {"label": "Belford Roxo",        "municipio": "Belford Roxo",       "bairro": "CENTRO"},
                33176787: {"label": "Niterói Centro",      "municipio": "Niterói",            "bairro": "CENTRO"},
                33055416: {"label": "Icaraí",              "municipio": "Niterói",            "bairro": "ICARAI"},
                33193991: {"label": "Itaipu",              "municipio": "Niterói",            "bairro": "ITAIPU"},
                33179301: {"label": "São Gonçalo",         "municipio": "São Gonçalo",        "bairro": "PARAISO"},
                33180660: {"label": "Alcântara",           "municipio": "São Gonçalo",        "bairro": "ALCANTARA"},
                33186928: {"label": "Maricá Centro",       "municipio": "Maricá",             "bairro": "CENTRO"},
                33203130: {"label": "Maricá Barroco",      "municipio": "Maricá",             "bairro": "BARROCO"},
                33166951: {"label": "Araruama",            "municipio": "Araruama",           "bairro": "CENTRO"},
                33184666: {"label": "Cabo Frio",           "municipio": "Cabo Frio",          "bairro": "PARQUE RIVIERA"},
                33196826: {"label": "Itaboraí",            "municipio": "Itaboraí",           "bairro": "CENTRO"},
                33021678: {"label": "Nova Friburgo",       "municipio": "Nova Friburgo",      "bairro": "CORDOEIRA"},
                33200068: {"label": "Volta Redonda",       "municipio": "Volta Redonda",      "bairro": "VILA SANTA CECILIA"},
            },
        },
        "pracas": [
            {"titulo": "Campo Grande", "municipio": "Rio de Janeiro", "nossa": 33183368,
             "diretos": [33520321, 33113114], "adjacentes": [],
             "nota": "Elite Campo Grande II (Senador Vasconcelos) sem dados no ENEM 2024 e 2025."},
            {"titulo": "Taquara", "municipio": "Rio de Janeiro", "nossa": 33187770,
             "diretos": [33169713, 33111642, 33173907], "adjacentes": [], "nota": ""},
            {"titulo": "Bangu", "municipio": "Rio de Janeiro", "nossa": 33187789,
             "diretos": [33159130], "adjacentes": [33122245],
             "nota": "Elite Realengo exibido como praça adjacente."},
            {"titulo": "Madureira", "municipio": "Rio de Janeiro", "nossa": 33197466,
             "diretos": [33140626, 33149780, 33094861, 33197350], "adjacentes": [],
             "nota": "Elite Madureira 3 sem dados no ENEM 2024 e 2025."},
            {"titulo": "Rocha Miranda", "municipio": "Rio de Janeiro", "nossa": 33192685,
             "diretos": [], "adjacentes": [33193649, 33193720],
             "nota": "Sem concorrente mapeado no bairro - exibidos os mais próximos (Irajá e Guadalupe)."},
            {"titulo": "Nova Iguaçu", "municipio": "Nova Iguaçu", "nossa": 33187762,
             "diretos": [33060355, 33185000, 33187681], "adjacentes": [33198926],
             "nota": "Elite Nova Iguaçu (bairro da Luz) sem dados no ENEM 2024 e 2025."},
            {"titulo": "Duque de Caxias", "municipio": "Duque de Caxias", "nossa": 33048185,
             "diretos": [], "adjacentes": [], "ref2024": [33173850],
             "nota": "O Elite de Caxias pontuou no ENEM 2024 (referência acima) e não registrou participantes em 2025. Santa Mônica de Caxias sem dados nos dois anos."},
            {"titulo": "São João de Meriti", "municipio": "São João de Meriti", "nossa": 33190674,
             "diretos": [33200572], "adjacentes": [], "ref2024": [33176752, 33185700],
             "nota": "Elite S. J. de Meriti e ZeroHum Jardim Metrópole pontuaram no ENEM 2024 (referências acima) e não registraram participantes em 2025."},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    "Apogeu": {
        "slug": "apogeu",
        "curto": "Apogeu",
        "cor": "#2563eb",
        "tile": "#1a3a6e",
        "logo": "Apogeu.imgtag",
        "html_out": "Concorrencia_Apogeu.html",
        "deploy_file": "apogeu.html",
        "hero_sub": "Comparação unidade a unidade com Santa Catarina, CAVE, Conexão, Jesuítas e Academia · Microdados INEP · Uso interno",
        "municipios_bench": {3136702: "Juiz de Fora"},
        "confronto_default": [31317101, 31354910],
        "cores_redes": {"Santa Catarina": "#be123c", "CAVE": "#0f766e", "Conexão": "#b45309",
                        "Jesuítas": "#7c3aed", "Academia": "#ca8a04"},
        "concorrentes": {
            "Santa Catarina": {
                31074373: {"label": "Morro da Glória",   "municipio": "Juiz de Fora", "bairro": "MORRO DA GLORIA"},
            },
            "CAVE": {
                31354910: {"label": "Centro",            "municipio": "Juiz de Fora", "bairro": "CENTRO"},
            },
            "Conexão": {
                31310735: {"label": "Centro",            "municipio": "Juiz de Fora", "bairro": "CENTRO"},
                31233102: {"label": "São Mateus",        "municipio": "Juiz de Fora", "bairro": "SAO MATEUS"},
                31306266: {"label": "Nova Era",          "municipio": "Juiz de Fora", "bairro": "NOVA ERA"},
            },
            "Jesuítas": {
                31074098: {"label": "Centro",            "municipio": "Juiz de Fora", "bairro": "CENTRO"},
            },
            "Academia": {
                31074101: {"label": "Centro",            "municipio": "Juiz de Fora", "bairro": "CENTRO"},
            },
        },
        "pracas": [
            {"titulo": "Santo Antônio I", "municipio": "Juiz de Fora", "nossa": 31317101,
             "diretos": [31354910, 31310735, 31074098, 31074101], "adjacentes": [31074373],
             "nota": "Colégio Santa Catarina (Morro da Glória) exibido como praça adjacente ao Centro."},
            {"titulo": "Santo Antônio II", "municipio": "Juiz de Fora", "nossa": 31356816,
             "diretos": [31354910, 31310735, 31074098, 31074101], "adjacentes": [31074373],
             "nota": "Mesma praça do Santo Antônio I (Centro)."},
            {"titulo": "Zona Norte", "municipio": "Juiz de Fora", "nossa": 31256285,
             "diretos": [31306266], "adjacentes": [], "nota": ""},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    "QI Bilíngue": {
        "slug": "qi",
        "curto": "QI",
        "cor": "#6d28d9",
        "tile": "#4c1d95",
        "logo": "QI_Bilíngue.imgtag",
        "html_out": "Concorrencia_QI.html",
        "deploy_file": "qi.html",
        "hero_sub": "Comparação unidade a unidade com Pensi, Alfa CEM, pH e AZ · Microdados INEP · Uso interno",
        "municipios_bench": {3304557: "Rio de Janeiro"},
        "confronto_default": [33135924, 33161011],
        "cores_redes": {"Pensi": "#ca8a04", "Alfa CEM": "#0f766e", "pH": "#be123c", "AZ": "#1d4ed8"},
        "concorrentes": {
            "Pensi": {
                33135827: {"label": "Maracanã",            "municipio": "Rio de Janeiro", "bairro": "MARACANA"},
                33166820: {"label": "Tijuca",              "municipio": "Rio de Janeiro", "bairro": "TIJUCA"},
                33067813: {"label": "Martins Vila Isabel", "municipio": "Rio de Janeiro", "bairro": "VILA ISABEL"},
                33071683: {"label": "Martins Méier",       "municipio": "Rio de Janeiro", "bairro": "MEIER"},
                33161011: {"label": "Freguesia",           "municipio": "Rio de Janeiro", "bairro": "FREGUESIA"},
                33138028: {"label": "Recreio 1",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33161402: {"label": "Recreio 2",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33193118: {"label": "Flamengo",            "municipio": "Rio de Janeiro", "bairro": "FLAMENGO"},
                33421226: {"label": "Copacabana",          "municipio": "Rio de Janeiro", "bairro": "COPACABANA"},
                33166935: {"label": "Jardim Carioca",      "municipio": "Rio de Janeiro", "bairro": "JARDIM CARIOCA"},
                33166943: {"label": "Madureira",           "municipio": "Rio de Janeiro", "bairro": "MADUREIRA"},
                33191824: {"label": "Vila da Penha",       "municipio": "Rio de Janeiro", "bairro": "VILA DA PENHA"},
                33057451: {"label": "Icaraí 1",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33150931: {"label": "Icaraí 2",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33165920: {"label": "Icaraí 3",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33161429: {"label": "Itaipu",              "municipio": "Niterói",        "bairro": "ITAIPU"},
                33027781: {"label": "Cabo Frio 1",         "municipio": "Cabo Frio",      "bairro": "CENTRO"},
                33178968: {"label": "Cabo Frio 2",         "municipio": "Cabo Frio",      "bairro": "CENTRO"},
                33178976: {"label": "Cabo Frio 3",         "municipio": "Cabo Frio",      "bairro": "CENTRO"},
                33120544: {"label": "Campos",              "municipio": "Campos dos Goytacazes", "bairro": "CENTRO"},
                33178909: {"label": "Petrópolis",          "municipio": "Petrópolis",     "bairro": "CENTRO"},
                33182094: {"label": "Teresópolis",         "municipio": "Teresópolis",    "bairro": "ALTO"},
            },
            "Alfa CEM": {
                33178879: {"label": "Anil",                "municipio": "Rio de Janeiro", "bairro": "ANIL"},
                33184720: {"label": "Barra Olímpica",      "municipio": "Rio de Janeiro", "bairro": "BARRA OLIMPICA"},
                33184739: {"label": "Barra da Tijuca 1",   "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33196273: {"label": "Barra da Tijuca 2",   "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33188092: {"label": "Recreio 1",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33193258: {"label": "Recreio 2",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33202532: {"label": "Recreio 3",           "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
            },
            "pH": {
                33105405: {"label": "Tijuca",              "municipio": "Rio de Janeiro", "bairro": "TIJUCA"},
                33110328: {"label": "Botafogo 1",          "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33158240: {"label": "Botafogo 2",          "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33249202: {"label": "Leblon",              "municipio": "Rio de Janeiro", "bairro": "LEBLON"},
                33155852: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33177627: {"label": "Recreio",             "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33180539: {"label": "Freguesia",           "municipio": "Rio de Janeiro", "bairro": "FREGUESIA"},
                33153450: {"label": "Icaraí 1",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33177619: {"label": "Icaraí 2",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33180385: {"label": "Icaraí 3",            "municipio": "Niterói",        "bairro": "ICARAI"},
                33165998: {"label": "Piratininga",         "municipio": "Niterói",        "bairro": "PIRATININGA"},
                33204039: {"label": "São João da Barra",   "municipio": "São João da Barra", "bairro": ""},
            },
            "AZ": {
                33173990: {"label": "Tijuca",              "municipio": "Rio de Janeiro", "bairro": "TIJUCA"},
                33228604: {"label": "Botafogo",            "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33447225: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33203431: {"label": "Recreio",             "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
                33223203: {"label": "Méier",               "municipio": "Rio de Janeiro", "bairro": "MEIER"},
                33175195: {"label": "Ilha",                "municipio": "Rio de Janeiro", "bairro": "JARDIM GUANABARA"},
            },
        },
        "pracas": [
            {"titulo": "Freguesia", "municipio": "Rio de Janeiro", "nossa": 33135924,
             "diretos": [33161011, 33180539], "adjacentes": [], "nota": ""},
            {"titulo": "Méier (Metropolitano)", "municipio": "Rio de Janeiro", "nossa": 33071721,
             "diretos": [33071683, 33223203], "adjacentes": [33067813], "nota": ""},
            {"titulo": "Recreio", "municipio": "Rio de Janeiro", "nossa": 33156026,
             "diretos": [33138028, 33161402, 33177627, 33203431, 33188092, 33193258, 33202532],
             "adjacentes": [], "nota": ""},
            {"titulo": "Rio 2 (Barra Olímpica)", "municipio": "Rio de Janeiro", "nossa": 33199400,
             "diretos": [33184720], "adjacentes": [33155852, 33447225, 33184739, 33196273],
             "nota": "Unidades da Barra da Tijuca exibidas como praças adjacentes."},
            {"titulo": "Rio 2 Bilíngue", "municipio": "Rio de Janeiro", "nossa": 33187924,
             "diretos": [33184720], "adjacentes": [33155852, 33447225, 33184739, 33196273],
             "nota": "A unidade QI - Rio 2 (regular) não registrou participantes no ENEM 2025; a praça é representada pela unidade bilíngue."},
            {"titulo": "Tijuca (Maracanã)", "municipio": "Rio de Janeiro", "nossa": 33124418,
             "diretos": [33135827, 33166820, 33105405, 33173990], "adjacentes": [], "nota": ""},
            {"titulo": "Botafogo", "municipio": "Rio de Janeiro", "nossa": 33143331,
             "diretos": [33110328, 33158240, 33228604], "adjacentes": [33193118],
             "nota": "A unidade QI Bilíngue Botafogo foi encerrada para 2026; dados referem-se a 2025."},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    "Cubo Global": {
        "slug": "cubo",
        "curto": "Cubo",
        "cor": "#0f9d96",
        "tile": "#097570",
        "logo": "Cubo_Global.imgtag",
        "html_out": "Concorrencia_Cubo.html",
        "deploy_file": "cubo.html",
        "hero_sub": "Comparação unidade a unidade com AZ, Pensi, pH, Alfa CEM e CEL · Microdados INEP · Uso interno",
        "municipios_bench": {3304557: "Rio de Janeiro"},
        "confronto_default": [33186260, 33110328],
        "cores_redes": {"AZ": "#1d4ed8", "Pensi": "#ca8a04", "pH": "#be123c",
                        "Alfa CEM": "#ea580c", "CEL": "#7c3aed"},
        "concorrentes": {
            "AZ": {
                33228604: {"label": "Botafogo",            "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33447225: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
            },
            "Pensi": {
                33193118: {"label": "Flamengo",            "municipio": "Rio de Janeiro", "bairro": "FLAMENGO"},
                33421226: {"label": "Copacabana",          "municipio": "Rio de Janeiro", "bairro": "COPACABANA"},
                33161402: {"label": "Recreio",             "municipio": "Rio de Janeiro", "bairro": "RECREIO"},
            },
            "pH": {
                33110328: {"label": "Botafogo 1",          "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33158240: {"label": "Botafogo 2",          "municipio": "Rio de Janeiro", "bairro": "BOTAFOGO"},
                33155852: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
            },
            "Alfa CEM": {
                33184739: {"label": "Barra da Tijuca 1",   "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
                33196273: {"label": "Barra da Tijuca 2",   "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
            },
            "CEL": {
                33176760: {"label": "Jardim Botânico",     "municipio": "Rio de Janeiro", "bairro": "JARDIM BOTANICO"},
                33065195: {"label": "Maria Angélica",      "municipio": "Rio de Janeiro", "bairro": "JARDIM BOTANICO"},
                33105154: {"label": "Barra da Tijuca",     "municipio": "Rio de Janeiro", "bairro": "BARRA DA TIJUCA"},
            },
        },
        "pracas": [
            {"titulo": "Botafogo", "municipio": "Rio de Janeiro", "nossa": 33186260,
             "diretos": [33110328, 33158240, 33228604],
             "adjacentes": [33193118, 33421226, 33176760, 33065195],
             "nota": "Pensi (Flamengo e Copacabana) e CEL (Jardim Botânico e Maria Angélica) exibidos como praças adjacentes - as duas redes não têm unidade em Botafogo. pH Botafogo 2 sem dados no ENEM 2024 e 2025."},
            {"titulo": "Barra da Tijuca (ABM)", "municipio": "Rio de Janeiro", "nossa": 33178828,
             "diretos": [33447225, 33155852, 33184739, 33196273, 33105154],
             "adjacentes": [33161402],
             "nota": "Pensi não tem unidade na Barra - a unidade do Recreio é exibida como adjacente. Alfa CEM Barra da Tijuca 2 sem dados no ENEM 2024 e 2025."},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    # RS: as duas telas compartilham o mesmo mapa de concorrentes de POA.
    # No ENEM 2025 as 14 primeiras escolas de Porto Alegre são exatamente as
    # deste mapa (régua INEP: presença completa + redação, n>=10).
    "Colégio Leonardo da Vinci": {
        "slug": "ldv",
        "curto": "LDV",
        "cor": "#0284c7",
        "tile": "#075985",
        "logo": "Colegio_Leonardo_da_Vinci.imgtag",
        "html_out": "Concorrencia_LDV.html",
        "deploy_file": "ldv.html",
        "hero_sub": "Comparação unidade a unidade com João Paulo I, Farroupilha, Fleming e as tradicionais de POA · Microdados INEP · Uso interno",
        "municipios_bench": {4314902: "Porto Alegre", 4304606: "Canoas"},
        "confronto_default": [43172423, 43213995],
        "cores_redes": {"João Paulo I": "#b45309", "Marista": "#1d4ed8", "Fleming": "#0f766e",
                        "Bertoni": "#65a30d", "Farroupilha": "#db2777", "Tradicionais POA": "#7c3aed"},
        "concorrentes": {
            "João Paulo I": {
                43173330: {"label": "Zona Sul",            "municipio": "Porto Alegre", "bairro": "IPANEMA"},
                43238203: {"label": "Higienópolis",        "municipio": "Porto Alegre", "bairro": "HIGIENOPOLIS"},
                43216684: {"label": "Praia de Belas",      "municipio": "Porto Alegre", "bairro": "PRAIA DE BELAS"},
            },
            "Marista": {
                43108164: {"label": "Rosário",             "municipio": "Porto Alegre", "bairro": "INDEPENDENCIA"},
                43178740: {"label": "Ipanema",             "municipio": "Porto Alegre", "bairro": "IPANEMA"},
            },
            "Fleming": {
                43213995: {"label": "Rio Branco",          "municipio": "Porto Alegre", "bairro": "RIO BRANCO"},
            },
            "Bertoni": {
                43215050: {"label": "Auxiliadora",         "municipio": "Porto Alegre", "bairro": "AUXILIADORA"},
            },
            "Farroupilha": {
                43104975: {"label": "Três Figueiras",      "municipio": "Porto Alegre", "bairro": "TRES FIGUEIRAS"},
            },
            "Tradicionais POA": {
                43105009: {"label": "Colégio Militar",     "municipio": "Porto Alegre", "bairro": "FARROUPILHA"},
                43107419: {"label": "Mãe de Deus",         "municipio": "Porto Alegre", "bairro": "TRISTEZA"},
                43107494: {"label": "Pastor Dohms",        "municipio": "Porto Alegre", "bairro": "HIGIENOPOLIS"},
                43104983: {"label": "Israelita",           "municipio": "Porto Alegre", "bairro": "RIO BRANCO"},
                43105017: {"label": "Bom Conselho",        "municipio": "Porto Alegre", "bairro": "FLORESTA"},
                43105068: {"label": "Santa Inês",          "municipio": "Porto Alegre", "bairro": "PETROPOLIS"},
                43104991: {"label": "Maria Imaculada",     "municipio": "Porto Alegre", "bairro": "PRAIA DE BELAS"},
                43105408: {"label": "Adventista Camaquã",  "municipio": "Porto Alegre", "bairro": "CAMAQUA"},
                43105637: {"label": "Adventista M. Rondon", "municipio": "Porto Alegre", "bairro": "VILA IPIRANGA"},
            },
        },
        "pracas": [
            {"titulo": "Rio Branco / Higienópolis (Alfa)", "municipio": "Porto Alegre", "nossa": 43172423,
             "diretos": [43213995, 43104983, 43215050],
             "adjacentes": [43238203, 43107494, 43105009, 43108164],
             "nota": "Colégio Militar é rede federal (gratuito). Em 2025 a Alfa passou a operar no prédio do IPA, no mesmo bairro."},
            {"titulo": "Cristal / Zona Sul (Beta)", "municipio": "Porto Alegre", "nossa": 43172440,
             "diretos": [],
             "adjacentes": [43216684, 43104991, 43173330],
             "nota": "Sem concorrente mapeado no Cristal - exibidos os mais próximos (Praia de Belas e Zona Sul)."},
            {"titulo": "Canoas (Gama)", "municipio": "Canoas", "nossa": 43213278,
             "diretos": [], "adjacentes": [],
             "nota": "Sem concorrente mapeado em Canoas. A unidade não tem participantes vinculados no ENEM 2025 - números de referência do ENEM 2024."},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    # Unificado, Americano e União: marcas individuais (não são uma rede).
    # Nenhuma respondeu o Censo 2025 → sem vínculo no ENEM 2025; as telas
    # rodam em referência ENEM 2024 (nossa_ref2024).
    "Unificado": {
        "slug": "unificado",
        "curto": "Unificado",
        "cor": "#dc2626",
        "tile": "#7f1d1d",
        "logo": "",
        "html_out": "Concorrencia_Unificado.html",
        "deploy_file": "unificado.html",
        "hero_sub": "Zona Sul e Ramiro vs a concorrência de cada praça · Referência ENEM 2024 · Microdados INEP · Uso interno",
        "aviso": "O Unificado não respondeu o Censo Escolar 2025, e o ENEM só vincula aluno a escola pelo Censo do ano — por isso não existem números 2025 para as nossas unidades (as dos concorrentes são 2025 normais). As linhas marcadas ENEM 2024 são a última foto: Zona Sul NG 669,0 (8º de Porto Alegre) e Ramiro NG 662,5 (13º). Ação: responder o Censo 2026 devolve o Unificado ao ENEM por escola já na edição 2026. A âncora do grupo em POA com dados vivos é a tela LDV.",
        "selo_card": "Referência ENEM 2024 · Censo 2025 não respondido",
        "municipios_bench": {4314902: "Porto Alegre"},
        "confronto_default": [43173330, 43108164],
        "cores_redes": {"João Paulo I": "#b45309", "Marista": "#1d4ed8",
                        "Farroupilha": "#db2777", "Tradicionais POA": "#7c3aed"},
        "concorrentes": {
            "João Paulo I": {
                43173330: {"label": "Zona Sul",            "municipio": "Porto Alegre", "bairro": "IPANEMA"},
                43238203: {"label": "Higienópolis",        "municipio": "Porto Alegre", "bairro": "HIGIENOPOLIS"},
                43216684: {"label": "Praia de Belas",      "municipio": "Porto Alegre", "bairro": "PRAIA DE BELAS"},
            },
            "Marista": {
                43108164: {"label": "Rosário",             "municipio": "Porto Alegre", "bairro": "INDEPENDENCIA"},
                43178740: {"label": "Ipanema",             "municipio": "Porto Alegre", "bairro": "IPANEMA"},
            },
            "Farroupilha": {
                43104975: {"label": "Três Figueiras",      "municipio": "Porto Alegre", "bairro": "TRES FIGUEIRAS"},
            },
            "Tradicionais POA": {
                43107419: {"label": "Mãe de Deus",         "municipio": "Porto Alegre", "bairro": "TRISTEZA"},
                43104983: {"label": "Israelita",           "municipio": "Porto Alegre", "bairro": "RIO BRANCO"},
                43105017: {"label": "Bom Conselho",        "municipio": "Porto Alegre", "bairro": "FLORESTA"},
            },
        },
        "pracas": [
            {"titulo": "Tristeza / Zona Sul", "municipio": "Porto Alegre", "nossa": 43214754,
             "diretos": [43173330, 43107419], "adjacentes": [43178740],
             "nota": "Unificado Zona Sul foi o 8º de Porto Alegre no ENEM 2024 (NG 669,0)."},
            {"titulo": "Moinhos de Vento (Ramiro)", "municipio": "Porto Alegre", "nossa": 43186700,
             "diretos": [43108164, 43105017], "adjacentes": [43104983, 43104975],
             "nota": "Unificado Ramiro foi o 13º de Porto Alegre no ENEM 2024 (NG 662,5)."},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    "Americano": {
        "slug": "americano",
        "curto": "Americano",
        "cor": "#0891b2",
        "tile": "#155e75",
        "logo": "",
        "html_out": "Concorrencia_Americano.html",
        "deploy_file": "americano.html",
        "hero_sub": "Col. Metodista Americano vs a concorrência da Independência/Rio Branco · Referência ENEM 2024 · Microdados INEP · Uso interno",
        "aviso": "O Americano não respondeu o Censo Escolar 2025, e o ENEM só vincula aluno a escola pelo Censo do ano — por isso não existem números 2025 para a nossa unidade (os concorrentes são 2025 normais). A linha marcada ENEM 2024 é a última foto: NG 624,4 com 19 inscritos. Ação: responder o Censo 2026 devolve o Americano ao ENEM por escola já na edição 2026. A âncora do grupo em POA com dados vivos é a tela LDV.",
        "selo_card": "Referência ENEM 2024 · Censo 2025 não respondido",
        "municipios_bench": {4314902: "Porto Alegre"},
        "confronto_default": [43213995, 43108164],
        "cores_redes": {"João Paulo I": "#b45309", "Marista": "#1d4ed8", "Fleming": "#0f766e",
                        "Bertoni": "#65a30d", "Tradicionais POA": "#7c3aed"},
        "concorrentes": {
            "João Paulo I": {
                43173330: {"label": "Zona Sul",            "municipio": "Porto Alegre", "bairro": "IPANEMA"},
                43238203: {"label": "Higienópolis",        "municipio": "Porto Alegre", "bairro": "HIGIENOPOLIS"},
                43216684: {"label": "Praia de Belas",      "municipio": "Porto Alegre", "bairro": "PRAIA DE BELAS"},
            },
            "Marista": {
                43108164: {"label": "Rosário",             "municipio": "Porto Alegre", "bairro": "INDEPENDENCIA"},
                43178740: {"label": "Ipanema",             "municipio": "Porto Alegre", "bairro": "IPANEMA"},
            },
            "Fleming": {
                43213995: {"label": "Rio Branco",          "municipio": "Porto Alegre", "bairro": "RIO BRANCO"},
            },
            "Bertoni": {
                43215050: {"label": "Auxiliadora",         "municipio": "Porto Alegre", "bairro": "AUXILIADORA"},
            },
            "Tradicionais POA": {
                43104983: {"label": "Israelita",           "municipio": "Porto Alegre", "bairro": "RIO BRANCO"},
                43107494: {"label": "Pastor Dohms",        "municipio": "Porto Alegre", "bairro": "HIGIENOPOLIS"},
            },
        },
        "pracas": [
            {"titulo": "Independência / Rio Branco", "municipio": "Porto Alegre", "nossa": 43107524,
             "diretos": [43213995, 43104983, 43215050, 43108164], "adjacentes": [43238203, 43107494],
             "nota": "Marista Rosário fica no mesmo eixo da Independência — exibido como concorrente direto."},
        ],
    },
    # ──────────────────────────────────────────────────────────────────────
    "União": {
        "slug": "uniao",
        "curto": "União",
        "cor": "#4338ca",
        "tile": "#312e81",
        "logo": "",
        "html_out": "Concorrencia_Uniao.html",
        "deploy_file": "uniao.html",
        "hero_sub": "Col. Metodista União vs a concorrência de Uruguaiana · Referência ENEM 2024 · Microdados INEP · Uso interno",
        "aviso": "O União não respondeu o Censo Escolar 2025, e o ENEM só vincula aluno a escola pelo Censo do ano — por isso não existem números 2025 para a nossa unidade (os concorrentes são 2025 normais). A linha marcada ENEM 2024 é a última foto: NG 573,5, 4º colégio de Uruguaiana, atrás de Laura Vicuña, Marista Sant'Ana e IF Farroupilha (federal). Ação: responder o Censo 2026 devolve o União ao ENEM por escola já na edição 2026.",
        "selo_card": "Referência ENEM 2024 · Censo 2025 não respondido",
        "municipios_bench": {4322400: "Uruguaiana"},
        "confronto_default": [43162290, 43162690],
        "cores_redes": {"Uruguaiana": "#ca8a04"},
        "concorrentes": {
            "Uruguaiana": {
                43162290: {"label": "Marista Sant'Ana",    "municipio": "Uruguaiana", "bairro": "CENTRO"},
                43162690: {"label": "Laura Vicuña",        "municipio": "Uruguaiana", "bairro": "CENTRO"},
                43050921: {"label": "IF Farroupilha",      "municipio": "Uruguaiana", "bairro": "CENTRO"},
            },
        },
        "pracas": [
            {"titulo": "Uruguaiana", "municipio": "Uruguaiana", "nossa": 43162703,
             "diretos": [43162290, 43162690], "adjacentes": [43050921],
             "nota": "IF Farroupilha é rede federal (gratuito). No ENEM 2024 o União foi o 4º da cidade, atrás de Laura Vicuña, Marista Sant'Ana e IF."},
        ],
    },
}


def get_marca(argv: list) -> tuple[str, dict]:
    nome = argv[1] if len(argv) > 1 else "Matriz Educação"
    if nome not in MARCAS:
        raise SystemExit(f"Marca desconhecida: {nome}. Opções: {list(MARCAS)}")
    return nome, MARCAS[nome]
